---
title: "Resume"
---

# Education

#### The University of British Columbia *-* September 2020 to May 2024

#### *Bachelor of Science in Mathematics* 

Key Modules: Advanced Multivariable Calculus, Linear Algebra, Statistical Computing, Data Structure & Algorithms

#### The University of British Columbia *-* Expected May 2025

#### *Master of Geomatics for Environmental Management* 

Key Modules: Landscape Ecology and Modeling, Geospatial Analysis, Environmental Management

# SKILLS

**Software:** Qgis, Arcgis, Python (sklearn, pandas, numpy, opencv), SQL, Matlab, java, MS Office

**Languages:** Mandarin (native), English (fluent), Cantonese (fluent), Japanese (basic)

# EXPERIENCE

**Hangzhou Eastern Communication Software Technology Co., Ltd*\|*** China **June – August 2023**

*Artificial Intelligence Intern*

-   Developed AR optical cross-connection box recognition code. Implemented algorithms to identify ports in images of the optical cross-connection box (utilizing OpenCV for dilation, erosion, color enhancement and extraction). Generated mesh based on the identified red points. Q

-   Developed a project aimed at identifying potential low-satisfaction users by analyzing user data. Utilized Python (sklearn) to train and compare various models. Contributed to API service development, docker image building and pushing.

-   Engaged in predicting potential degradation in internet, transmission, and voice specialized lines by leveraging data analysis and machine learning techniques. Cleaned 5000 rows of raw data to ensure data quality and relevance. Utilized sklearn to train and compare various machine learning models, with the goal of creating accurate prediction models for detecting degradation in these specialized lines.

-   Completed the development of the API service for potential low-satisfaction users on OTN special lines, including coding, docker image packaging and pushing.

-   Collaborated on the drafting of a software copyright for the AR optical cross-connection box resource calibration application system. Designed the software interface and providing instructions for interactive buttons.

# **ACTIVITIES**

**Electric Vehicle Mapping Project*\|*** UBC **August 2024 – Present**

Conducted research on how various spatial regions, road networks, and vehicle configurations impact EV range.

Calculated optimal routes based on EV regenerative braking

Displayed results on GIS maps for spatial analysis and decision support.

**Imagine UBC Orientation*\|*** UBC **August 2021**

*Orientation Leader*

Cultivated and nurtured communities of friendship and a sense of belonging for new UBC students.

Enhanced my abilities in group and online facilitation, effective communication, community development, and team building through active involvement and leadership in this event.

**UBC Notetaker*\|*** UBC **September 2023 – April 2024**

*Math 360 Notetaker*

Produced high-quality notes covering course highlights and key concepts to aid students with disabilities.

Utilized tools like Jupyter Notebook to create diverse and visually engaging notes with a combination of text, graphics, and examples to enhance learning effectiveness.
